/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sabonay.education.common;

/**
 *
 * @author Agyepong
 */
public enum MenuItem {
    ALL_ITEMS,
    
    TERM_REPORT_NOTE_ITEM,
    STUDENT_TERMINAL_REPORT_COMMENT_ITEM,
    MASS_STUDENT_BALANCE_ITEM,
    STUDENT_BILL_REPORT_ITEM,
    AUDIT_TRAY_ITEM,
    
    PASSWORD_CHANGE_ITEM,
    STUDENT_INFO_ITEM,
    STUDENT_CONTACTS_ITEM,
    STUDENT_ADMITTED_ITEM,
    STUDENT_SCHOLARSHIP_ITEM,
    STUDENT_MARKS_ITEM,
    STUDENT_BROADSHEET_ITEM,
    STUDENT_REPORT_ITEM,
    
    CLASS_MEMBERSHIP_ITEM,
  
    BILL_ITEM_PAID_ITEM,
    BILL_PAYMENT_REPORT_ITEM,
    DAILY_TRANSACTION_ITEM,
    CLEARANCE_FORM_ITEM,
    TRACE_CHECK_ITEM,
    SINGLE_STUDENT_BILL_ITEM,
    SINGLE_STUDENT_REPORT_ITEM,
    STUDENT_INITIAL_FINANCIAL_BALANCE_ITEM,
    STUDENT_BILL_ITEM,
    STUDENT_BILL_ITEMS_ITEM,
    STUDENT_CHARGES_ITEM,
    STUDENT_LEDGER_ITEM,
    STUDENT_BILL_TYPE,
    
    SCHOLARSHIP_ITEM,
    HOUSE_REPORT_ITEM,
    SUBJECT_COMBINATION_ITEM,
    
    SCHOOL_SETTINGS_ITEM,
    SCHOOL_STAFF_ITEM,
    SCHOOL_HOUSE_ITEM,
    SCHOOL_PROGRAM_ITEM,
    SCHOOL_SUBJECT_ITEM,
    SCHOOL_CLASS_ITEM,
    
    ACADEMIC_YEAR_ITEM,
    ACADEMIC_TERM_ITEM,
    ACADEMIC_YEAR_ACTIVE_CLASSES_ITEM,
    
    CONDUCT_REMARKS_ITEM,
    HEAD_REPORT_COMMENT_ITEM,
    
    CLASS_TEACHER_ITEM,
    CLASS_TEACHER_REPORT_COMMENT_ITEM,
    TEACHING_SUBJECT_ITEM,
    
    DISCIPLINE_RECORDS_ITEM,
    DISCIPLINE_RECORD_ITEMS_ITEM,
    
    MOCK_EXAM_MARKS_ITEM,
    MOCK_EXAM_BROADSHEET_ITEM,
    MID_EXAM_MARKS_ITEM,
    
    USER_ACCOUNTS_ITEM,
    
    GENERAL_REPORT_ITEM,
    
    SABONAY_ITEM,
    SYSTEM_SETTINGS_ITEM,
    GRADING_SYSTEM_ITEM,
    
    FEATURES_ITEM,
    RGROUPS_ITEM,
    USER_GROUPS_ITEM,
    USERS_ITEM,
    
    BIND_PROPERTIES_ITEM,
    SMS_BILL_AND_REPORT_ITEM,
    SMS_BLAST_ITEM,
    SMS_REPORT,
    HELP,
    TIME_TABLE,
    BREAK_TIME,
    HOLIDAYS,
    STUDENT_ALBUM
}
